name: KMP library compilation check

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cocoapods install
      run: (cd sample/ios-app && pod install)
    - name: Check library
      run: ./gradlew build publishToMavenLocal
    - name: Check iOS
      run: cd sample/ios-app && xcodebuild -scheme TestProj -workspace TestProj.xcworkspace -configuration Debug -sdk iphonesimulator -arch x86_64 build CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcpretty